### PR TITLE
CORTX-28953 : Conf.search without specifying any value is not supported

### PR DESCRIPTION
**Pull request by akash2144**
Signed-off-by: Ujjwal Lanjewar <ujjwal.lanjewar@seagate.com>

# Problem Statement
- Conf.search without specifying any value is not supported

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [x] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [x] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [x] Changes done to WIKI / Confluence page

### CODE REVIEW

**Comment by akash2144** [comment]
Tests :
1. Search for the key with val as None.
>>> from cortx.utils.conf_store import Conf
>>> from cortx.utils.cortx.const import Const
>>> Conf.load("cortx_conf", "yaml:///etc/cortx/cluster.conf")
>>> Conf.search('cortx_conf', 'node', 'type', None)
['node>11c733c5d1e649378b86a1db5e4828fc>type', 'node>139a017932ad49d6950674a5a2792be8>type', 'node>2a7bc47ac7b440b4a8b61d1b89e37922>storage>cvg[0]>type', 'node>2a7bc47ac7b440b4a8b61d1b89e37922>storage>cvg[1]>type', 'node>2a7bc47ac7b440b4a8b61d1b89e37922>type', 'node>6a61b6b00f114087a0091e5dcbe1355c>type', 'node>9413adcd52d04bf985f5a1c09ec435d3>storage>cvg[0]>type', 'node>9413adcd52d04bf985f5a1c09ec435d3>storage>cvg[1]>type', 'node>9413adcd52d04bf985f5a1c09ec435d3>type', 'node>98e306ca497041b7b30bb0817dc29294>type', 'node>af5aa0e2f2fa474da4d467513c90ebe3>storage>cvg[0]>type', 'node>af5aa0e2f2fa474da4d467513c90ebe3>storage>cvg[1]>type', 'node>af5aa0e2f2fa474da4d467513c90ebe3>type', 'node>b212175237ec4222a18d4774ad8dafd9>type']
>>>
2.  Search for the presence of key in the middle
>>> from cortx.utils.conf_store import Conf
>>> from cortx.utils.cortx.const import Const
>>> Conf.load("cortx_conf", "yaml:///etc/cortx/cluster.conf")
>>> Conf.search('cortx_conf', 'node', 'storage', None)
['node>2a7bc47ac7b440b4a8b61d1b89e37922>storage>cvg[0]>devices>data[0]', 'node>2a7bc47ac7b440b4a8b61d1b89e37922>storage>cvg[0]>devices>data[1]', 'node>2a7bc47ac7b440b4a8b61d1b89e37922>storage>cvg[0]>devices>metadata[0]', 'node>2a7bc47ac7b440b4a8b61d1b89e37922>storage>cvg[0]>name', 'node>2a7bc47ac7b440b4a8b61d1b89e37922>storage>cvg[0]>type', 'node>2a7bc47ac7b440b4a8b61d1b89e37922>storage>cvg[1]>devices>data[0]', 'node>2a7bc47ac7b440b4a8b61d1b89e37922>storage>cvg[1]>devices>data[1]', 'node>2a7bc47ac7b440b4a8b61d1b89e37922>storage>cvg[1]>devices>metadata[0]', 'node>2a7bc47ac7b440b4a8b61d1b89e37922>storage>cvg[1]>name', 'node>2a7bc47ac7b440b4a8b61d1b89e37922>storage>cvg[1]>type', 'node>2a7bc47ac7b440b4a8b61d1b89e37922>storage>cvg_count', 'node>9413adcd52d04bf985f5a1c09ec435d3>storage>cvg[0]>devices>data[0]', 'node>9413adcd52d04bf985f5a1c09ec435d3>storage>cvg[0]>devices>data[1]', 'node>9413adcd52d04bf985f5a1c09ec435d3>storage>cvg[0]>devices>metadata[0]', 'node>9413adcd52d04bf985f5a1c09ec435d3>storage>cvg[0]>name', 'node>9413adcd52d04bf985f5a1c09ec435d3>storage>cvg[0]>type', 'node>9413adcd52d04bf985f5a1c09ec435d3>storage>cvg[1]>devices>data[0]', 'node>9413adcd52d04bf985f5a1c09ec435d3>storage>cvg[1]>devices>data[1]', 'node>9413adcd52d04bf985f5a1c09ec435d3>storage>cvg[1]>devices>metadata[0]', 'node>9413adcd52d04bf985f5a1c09ec435d3>storage>cvg[1]>name', 'node>9413adcd52d04bf985f5a1c09ec435d3>storage>cvg[1]>type', 'node>9413adcd52d04bf985f5a1c09ec435d3>storage>cvg_count', 'node>af5aa0e2f2fa474da4d467513c90ebe3>storage>cvg[0]>devices>data[0]', 'node>af5aa0e2f2fa474da4d467513c90ebe3>storage>cvg[0]>devices>data[1]', 'node>af5aa0e2f2fa474da4d467513c90ebe3>storage>cvg[0]>devices>metadata[0]', 'node>af5aa0e2f2fa474da4d467513c90ebe3>storage>cvg[0]>name', 'node>af5aa0e2f2fa474da4d467513c90ebe3>storage>cvg[0]>type', 'node>af5aa0e2f2fa474da4d467513c90ebe3>storage>cvg[1]>devices>data[0]', 'node>af5aa0e2f2fa474da4d467513c90ebe3>storage>cvg[1]>devices>data[1]', 'node>af5aa0e2f2fa474da4d467513c90ebe3>storage>cvg[1]>devices>metadata[0]', 'node>af5aa0e2f2fa474da4d467513c90ebe3>storage>cvg[1]>name', 'node>af5aa0e2f2fa474da4d467513c90ebe3>storage>cvg[1]>type', 'node>af5aa0e2f2fa474da4d467513c90ebe3>storage>cvg_count']
>>>

**Comment by akash2144** [comment]
Test Case results :
```
[root@cortx-ha-headless-svc conf_store]# python3 -m unittest test_conf_store.TestConfStore.test_conf_store_search_keys -v
test_conf_store_search_keys (test_conf_store.TestConfStore)
Test conf store search key API by passing None value. ... ok

----------------------------------------------------------------------
Ran 1 test in 0.161s

OK
```

**Review by ArchanaLimaye — APPROVED** [review]

**Review by rahul-tripathi-git — APPROVED** [review]
+1

**Review by suryakumar1024 — APPROVED** [review]

**Comment by rahul-tripathi-git** [comment]
test this please

**Review by ujjwalpl — APPROVED** [review]

**Pull request merged**
