### PR TITLE
EOS-14572: ADDB : Code refactor (utils repo)

### PR DESCRIPTION
**Pull request by pratyush-seagate**
#  EOS-14572: ADDB : Code refactor (utils repo)

## Checklist
- [x] **Compilation:** _This patch does not break compilation_
- [x] **Merge conflicts:** _This patch has been squashed and re-based, it can be merged using fast-forward merge_
- [] **Code review:** _All discussions have been resolved_
- [x] **Sanity Testing:** _All Unit tests are passing and able to do mount and io operations works from NFS client_
- [x] **Documentation:** _This patch and merge request have up to date description_
- [x] **Unit Testing and debugging:** _Both single and multi node changes are unit tested_

## UT
[root@ssc-vm-c-0040 /]# ./cortx-posix/scripts/test.sh
 --
 --
Configuration Completed
Clean indexes prepared
NSAL Unit tests
NS Tests
Test results are logged to /var/log/cortx/test/ut/ut_nsal.log
Total tests  = 5
Tests passed = 5
Tests failed = 0

Iterator test
Test results are logged to /var/log/cortx/test/ut/ut_nsal.log
Total tests  = 2
Tests passed = 2
Tests failed = 0

KVTree test
Test results are logged to /var/log/cortx/test/ut/ut_nsal.log
Total tests  = 17
Tests passed = 17
Tests failed = 0

Global KVS Tests
Test results are logged to /var/log/cortx/test/ut/ut_nsal.log
Total tests  = 4
Tests passed = 4
Tests failed = 0

CORTXFS Unit tests
Endpoint ops Tests
Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.logs
Total tests  = 4
Tests passed = 4
Tests failed = 0

FS Tests
Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
Total tests  = 3
Tests passed = 3
Tests failed = 0

Directory tests
Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
Total tests  = 14
Tests passed = 14
Tests failed = 0

File creation tests
Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
Total tests  = 4
Tests passed = 4
Tests failed = 0

Link Tests
Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
Total tests  = 6
Tests passed = 6
Tests failed = 0

Rename tests
Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
Total tests  = 3
Tests passed = 3
Tests failed = 0

Attribute Tests
Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
Total tests  = 5
Tests passed = 5
Tests failed = 0

Xattr file Tests
Test results are logged to /var/log/cortx/test/ut/xattr_file_ops.log
Total tests  = 9
Tests passed = 9
Tests failed = 0

Xattr dir Tests
Test results are logged to /var/log/cortx/test/ut/xattr_dir_ops.log
Total tests  = 9
Tests passed = 9
Tests failed = 0

IO tests
Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
Total tests  = 7
Tests passed = 7
Tests failed = 0

DSAL Unit tests
Dsal basic test
Test results are logged to /var/log/cortx/test/ut/ut_dsal.log
Total tests  = 11
Tests passed = 11
Tests failed = 0

Dsal IO test
Test results are logged to /var/log/cortx/test/ut/ut_dsal.log
Total tests  = 2
Tests passed = 2
Tests failed = 0

Dsal space stats test
Test results are logged to /var/log/cortx/test/ut/ut_dsal.log
Total tests  = 2
Tests passed = 2
Tests failed = 0

## Commit Message
commit 108fa3b0f179158df02f8e9908aff52a0fb8a768
Author: pratyush-seagate <pratyush.k.khan@seagate.com>
Date:   Mon Nov 2 16:56:33 2020 -0700

        EOS-14572: ADDB : Code refactor (utils repo)
        List of modified files:
                modified:   c-utils/src/CMakeLists.txt
                deleted:    c-utils/src/addb/CMakeLists.txt
                deleted:    c-utils/src/addb/plugin.c
                modified:   c-utils/src/cortx/m0common.c
                modified:   c-utils/src/cortx/m0kvs.c
                modified:   c-utils/src/cortx/m0store.c
                new file:   c-utils/src/include/cfs_utils_perfc.h
                modified:   c-utils/src/include/perf/perf-counters.h
        Change description:
                Refactor function tags, maps and attribute enums and move out repo specific code. Introduce ranges. move out plugin.
        Test:
                On VM: UT, addb traces and graphs

### CODE REVIEW

**Review by AtitaShirwaikar — APPROVED** [review]
+1

**Review by shahidSTX — APPROVED** [review]
LGTM

**Review by Anilsindhi — APPROVED** [review]
LGTM, +1

**Review by vimalraghwani20 — APPROVED** [review]

**Comment by pratyush-seagate** [comment]
This has been replaced by https://github.com/Seagate/cortx-utils/pull/77

**Pull request closed without merging**
