### PR TITLE
EOS-16256: Instantiation of Event message and its attributes

### PR DESCRIPTION
**Pull request by selvakumaar5496**
# Problem Statement
- IEM send and receive interfaces

# Design
- https://seagatetechnology.sharepoint.com/:w:/r/sites/gteamdrv1/tdrive1224/_layouts/15/doc2.aspx?sourcedoc=%7BA30E4234-9D8D-4342-9115-292515234511%7D&file=CORTX%20IEM%20Specification.docx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1621843798956&wdOrigin=OFFICECOM-WEB.MAIN.OTHER&cid=80c8129b-9989-4d62-a223-2d021f559116

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [x] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [x] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [x] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [x] Jira is updated
- [x] Check if the description is clear and explained. 
- [x] Check Acceptance Criterion is defined. 
- [x] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [x] Changes done to WIKI / Confluence page
Note: Re-raised this PR for https://github.com/Seagate/cortx-utils/pull/278

### CODE REVIEW

**Review by sachinpunadikar — APPROVED** [review]
+1

**Comment by rahul-tripathi-git** [comment]
test this please

**Review by rahul-tripathi-git — APPROVED** [review]
+1

**Comment by sachinpunadikar** [comment]
test this please

**Comment by sachinpunadikar** [comment]
test this please

**Pull request merged**
