### PR TITLE
ConfStore: search functionality based on key and value

### PR DESCRIPTION
**Pull request by vimalraghwani20**
# Problem Statement
ConfStore: search functionality based on key and value

# Design
-  Added Search API in the constore based on key and value

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]:  Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: Y
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: Y
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [x] Jira is updated
- [x] Check if the description is clear and explained. 
- [x] Check Acceptance Criterion is defined. 
- [x] All the tests performed should be mentioned before Resolving a JIRA. 
- [x] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

Tested the changes with the custom build on kubernetes 
http://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.9/job/cortx-all-image-custom-ci/1227/

### CODE REVIEW

**Review by sachinpunadikar — CHANGES_REQUESTED** [review]
Please add test cases
Not clear on default value of "val" as "none". Please add flow for val as none.

**Review by rahul-tripathi-git — CHANGES_REQUESTED** [review]
Please verify if search interface should be added in ConsulKVPayload and/or IniKVPayload.
https://github.com/Seagate/cortx-utils/blob/kubernetes/py-utils/src/utils/kv_store/kv_store_collection.py

**Review by sachinpunadikar — APPROVED** [review]
+1

**Review by rahul-tripathi-git — APPROVED** [review]
Next steps for search interface: 
- Test cases needs to be added,

-  Other KV payloads eg. consul, ini etx needs to be updated with search interface,

**Pull request merged**
