### PR TITLE
Checking whether zookeeper and kafka services are running - post_install phase

### PR DESCRIPTION
**Pull request by vastradparayya**
Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

### CODE REVIEW

**Review by rahul-tripathi-git — APPROVED** [review]
Looks good.

**Comment by rahul-tripathi-git** [comment]
run mini-provisioning

**Review by ujjwalpl — APPROVED** [review]

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by sachinpunadikar — APPROVED** [review]
+1

**Pull request merged**
