### PR TITLE
Added root permission for build, install and uninstall

### PR DESCRIPTION
**Pull request by vastradparayya**
Added root(sudo) permission in READ.md

# Problem Statement
- Error in building and installing without root permission

# Design
-  https://github.com/Seagate/cortx-utils/issues/342

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: NA
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: NA
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: NA
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

### CODE REVIEW

**Review by sachinpunadikar — CHANGES_REQUESTED** [review]
Please add explicitly that one need to be privileged user (root) for building cortx-py-utils & install the same. This should go in as text in build & install section.
"sudo" indicates the same, but its indirect indication.

**Comment by sachinpunadikar** [comment]
Oops, I conveyed in wrong way, my bad .. 
Please keep the sudo , that change is required along-with your current change

**Review by sachinpunadikar — APPROVED** [review]
+1

**Review by rahul-tripathi-git — APPROVED** [review]
Looks good to me

**Review by selvakumaar5496 — APPROVED** [review]

**Comment by sachinpunadikar** [comment]
VM deployment is success - http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/PyUtils/570/console

**Pull request merged**
