### PR TITLE
Fix Codacy issue: unused import, re imported & trailing white space

### PR DESCRIPTION
**Pull request by rohit-k-dwivedi**
Signed-off-by: Rohit Dwivedi <rohit.k.dwivedi@seagate.com>

# Problem Statement
- Fixing Codacy Issue

# Design
- Fixed unused **import** & **re imported** issues

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]:
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:
- Confirm that Test Cases are added for new features added [Y/N]: 
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  

# Review Checklist 
####  Before posting the PR please ensure:
- [x] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] New package/s added to setup.py?
- [x] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified.

# KVstore/Confstore feature (changes/fixes) checklist
#### Confirm changes are made for:
- [ ] ConfStore
- [ ] KVStore
- [ ] ConfCli
- [ ] Test cases added for all above 3
- [ ] changes done in all the KVpayloads (ConsulKvPayload, IniKvPayload, KvPayload)

# Documentation
- [ ] Changes done to WIKI / Confluence page

-----
[View rendered c-utils/README.md](https://github.com/Seagate/cortx-utils/blob/CORTX-30478/c-utils/README.md)

### CODE REVIEW

**Review by sachinpunadikar — CHANGES_REQUESTED** [review]
Why you are removing these files ?

**Comment by sachinpunadikar** [comment]
Do not remove these files

**Comment by rohit-k-dwivedi** [comment]
@sachinpunadikar , these are no longer in by any team, and are adding up to codacy errors

**Comment by sachinpunadikar** [comment]
In that case move this code to some other repo & then remove from here

**Comment by rohit-k-dwivedi** [comment]
> In that case move this code to some other repo & then remove from here
it was a miscommunication, not removing any code now, just those directories will be ignored in codacy

**Review by cdeshmukh — APPROVED** [review]

**Review by suryakumar1024 — APPROVED** [review]

**Comment by cdeshmukh** [comment]
@rohit-k-dwivedi pr needs rebase

**Pull request merged**
