### PR TITLE
CORTX-29735: Support bundle enabling filter flags to component

### PR DESCRIPTION
**Pull request by suryakumar1024**
# Problem Statement
- Since motr component support bundle scripts fails due to filter flags passed to it, In support bundle framework existing code we have disabled the filter flags to component level support bundle script.

# Design
-  Need to revert back the disabled code and allow SB framework to pass all the filter flags to Component SB scripts.
- Motr component also making the changes to accept filter flags in to its motr component SB script. (This PR can be only merged once Motr changes are merged.)

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [x] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: NA
- [x] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: NA
- [x] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [x] Is there a change in filename/package/module or signature [Y/N]: Y
- [x] If yes for above point, Is a notification sent to all other cortx components [Y/N]: Y
- [x] Jira is updated
- [x] Check if the description is clear and explained. 
- [x] Check Acceptance Criterion is defined. 
- [x] All the tests performed should be mentioned before Resolving a JIRA. 
- [x] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

### CODE REVIEW

**Comment by gargpalak048** [comment]
Hi @suryakumar1024 
Please do the integration testing and check that all the component's support bundle is generating successfully or not.
only after that this PR should merge.

**Review by sachitanands — APPROVED** [review]
looks good

**Review by cdeshmukh — APPROVED** [review]

**Comment by cdeshmukh** [comment]
Look at codacy issues, 1N deployment failure & rebase PR

**Review by rohit-k-dwivedi — APPROVED** [review]

**Comment by suryakumar1024** [comment]
Executed support bundle script generation script in Kubernetes cluster

Success output

```
[root@ssc-vm-g2-rhev4-3177 k8_cortx_cloud]# ./logs-cortx-cloud.sh
######################################################
# ✍️  Generating logs, namespace: default, date: 2022-04-05_07-41
######################################################

🔍 Logging pod: consul-client-hthg7
🔍 Logging pod: consul-server-0
🔍 Logging pod: cortx-control-855f79f4bc-tlskx, container: cortx-csm-agent
 ⭐ Generating support-bundle logs for pod: cortx-control-855f79f4bc-tlskx
Please use the below bundle id for checking the status of support bundle.
---------------------------------------------------------------
| bundle-logs-cortx-control-855f79f4bc-tlskx-2022-04-05_07-41 |
---------------------------------------------------------------
Please Find the file on -> /var/cortx/support_bundle/bundle-logs-cortx-control-855f79f4bc-tlskx-2022-04-05_07-41 .

tar: Removing leading `/' from member names

🔍 Logging pod: cortx-data-ssc-vm-g2-rhev4-3177-6ff66f9958-xm9s9, container: cortx-hax
🔍 Logging pod: cortx-data-ssc-vm-g2-rhev4-3177-6ff66f9958-xm9s9, container: cortx-motr-confd
🔍 Logging pod: cortx-data-ssc-vm-g2-rhev4-3177-6ff66f9958-xm9s9, container: cortx-motr-io-001
🔍 Logging pod: cortx-data-ssc-vm-g2-rhev4-3177-6ff66f9958-xm9s9, container: cortx-motr-io-002
 ⭐ Generating support-bundle logs for pod: cortx-data-ssc-vm-g2-rhev4-3177-6ff66f9958-xm9s9
Please use the below bundle id for checking the status of support bundle.
---------------------------------------------------------------------------------
| bundle-logs-cortx-data-ssc-vm-g2-rhev4-3177-6ff66f9958-xm9s9-2022-04-05_07-41 |
---------------------------------------------------------------------------------
Please Find the file on -> /var/cortx/support_bundle/bundle-logs-cortx-data-ssc-vm-g2-rhev4-3177-6ff66f9958-xm9s9-2022-04-05_07-41 .

tar: Removing leading `/' from member names

🔍 Logging pod: cortx-ha-645558c79c-hj9jl, container: cortx-ha-fault-tolerance
🔍 Logging pod: cortx-ha-645558c79c-hj9jl, container: cortx-ha-health-monitor
🔍 Logging pod: cortx-ha-645558c79c-hj9jl, container: cortx-ha-k8s-monitor
 ⭐ Generating support-bundle logs for pod: cortx-ha-645558c79c-hj9jl
Please use the below bundle id for checking the status of support bundle.
----------------------------------------------------------
| bundle-logs-cortx-ha-645558c79c-hj9jl-2022-04-05_07-41 |
----------------------------------------------------------
Please Find the file on -> /var/cortx/support_bundle/bundle-logs-cortx-ha-645558c79c-hj9jl-2022-04-05_07-41 .

tar: Removing leading `/' from member names

🔍 Logging pod: cortx-server-ssc-vm-g2-rhev4-3177-c5f9454fd-kmjlh, container: cortx-rgw
🔍 Logging pod: cortx-server-ssc-vm-g2-rhev4-3177-c5f9454fd-kmjlh, container: cortx-hax
 ⭐ Generating support-bundle logs for pod: cortx-server-ssc-vm-g2-rhev4-3177-c5f9454fd-kmjlh
Please use the below bundle id for checking the status of support bundle.
----------------------------------------------------------------------------------
| bundle-logs-cortx-server-ssc-vm-g2-rhev4-3177-c5f9454fd-kmjlh-2022-04-05_07-41 |
----------------------------------------------------------------------------------
Please Find the file on -> /var/cortx/support_bundle/bundle-logs-cortx-server-ssc-vm-g2-rhev4-3177-c5f9454fd-kmjlh-2022-04-05_07-41 .

tar: Removing leading `/' from member names

🔍 Logging pod: kafka-0
🔍 Logging pod: zookeeper-0

📦 "logs-cortx-cloud-2022-04-05_07-41.tar" file generated
✔️  All done

```

**Comment by suryakumar1024** [comment]
> Hi @suryakumar1024 Please do the integration testing and check that all the component's support bundle is generating successfully or not. only after that this PR should merge.

Tested and posted Results above

**Review by rahul-tripathi-git — APPROVED** [review]

**Review by ujjwalpl — APPROVED** [review]

**Pull request merged**
