### PR TITLE
EOS-20849: Template for utils_setup

### PR DESCRIPTION
**Pull request by selvakumaar5496**
# Problem Statement
Template for utils_setup

# Design
Key was missing in template file of config phase

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: N 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: N
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  N
Note: No testcases since it is updating of template files

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [x] Jira is updated
- [x] Check if the description is clear and explained. 
- [x] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page
Note: WIKI will be automatically updated once this gets merged.

### CODE REVIEW

**Review by sachinpunadikar — APPROVED** [review]
+1

**Review by rahul-tripathi-git — APPROVED** [review]
Looks good to me

**Comment by sachinpunadikar** [comment]
@priyankdal , @gauravchaudhari02  please make relevant changes to the mini-provisioning jobs

**Comment by sachinpunadikar** [comment]
test this please

**Comment by sachinpunadikar** [comment]
test this please

**Comment by sachinpunadikar** [comment]
VM deployment is successful - http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/PyUtils/349/console

**Pull request merged**
