### PR TITLE
CORTX-29185: Fix ConfStore-CLI get_diff test case

### PR DESCRIPTION
**Pull request by suryakumar1024**
# Problem Statement
- conf_store CLI test 'test_conf_cli_by_get_diff' is failing.

# Design
-  Fixed ConfStore CLI diff -> get call implementation with arg.format as none
-  Fixed test case by making deepcopy of files configs

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [x] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: Y
- [x] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: Y
- [x] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [x] Is there a change in filename/package/module or signature [Y/N]: N
- [x] If yes for above point, Is a notification sent to all other cortx components [Y/N]: NA
- [x] Jira is updated
- [x] Check if the description is clear and explained. 
- [x] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

### CODE REVIEW

**Comment by rohit-k-dwivedi** [comment]
tried testing with both versions of urllib 1.21.1 and 1.26.8
seeing this error
```
-bash-4.2$ python3 -m unittest conf_store.test_conf_cli.TestConfCli.test_conf_cli_by_get_diff
> /home/932781/cortx-utils/py-utils/test/conf_store/test_conf_cli.py(86)test_conf_cli_by_get_diff()
-> cmd = "conf json:///tmp/file1.json diff json:///tmp/file2.json -k version;branch"
(Pdb) c
F
======================================================================
FAIL: test_conf_cli_by_get_diff (conf_store.test_conf_cli.TestConfCli)
Test by retrieving a value using get api
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/932781/cortx-utils/py-utils/test/conf_store/test_conf_cli.py", line 86, in test_conf_cli_by_get_diff
    cmd = "conf json:///tmp/file1.json diff json:///tmp/file2.json -k version;branch"
AssertionError: False is not true : b'\'Namespace\' object has no attribute \'format\'\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.6/site-packages/cortx/utils/conf_store/conf_cli.py", line 334, in main\n    out = args.func(args)\n  File "/usr/lib/python3.6/site-packages/cortx/utils/conf_store/conf_cli.py", line 95, in diff\n    string_1 = ConfCli.get(args)\n  File "/usr/lib/python3.6/site-packages/cortx/utils/conf_store/conf_cli.py", line 81, in get\n    format_type = \'json\' if args.format == None else args.format\nAttributeError: \'Namespace\' object has no attribute \'format\'\n\n'
----------------------------------------------------------------------
Ran 1 test in 1.736s
FAILED (failures=1)
-bash-4.2$
```

**Comment by suryakumar1024** [comment]
@rohit-k-dwivedi 
Hi I mentioned the same in JIRA ticket with required version for urllib3 package

I get below error message

pkg_resources.ContextualVersionConflict: (urllib3 1.25 (/usr/local/lib/python3.6/site-packages), Requirement.parse('urllib3<1.25,>=1.21.1'),

{'requests'}
)

Required urllib version
urllib version should be urllib3<1.25,>=1.21.1

pip3 install urllib3==1.24.3

**Review by selvakumaar5496 — APPROVED** [review]

**Review by selvakumaar5496 — APPROVED** [review]
I hope all test codes are working fine.

**Comment by rohit-k-dwivedi** [comment]
getting the same issue with your recommended version of urliib
```-bash-4.2$ pip3 list|grep urllib
urllib3            1.24.3

-bash-4.2$ python3 -m unittest conf_store.test_conf_cli.TestConfCli.test_conf_cli_by_get_diff
> /home/932781/cortx-utils/py-utils/test/conf_store/test_conf_cli.py(86)test_conf_cli_by_get_diff()
-> cmd = "conf json:///tmp/file1.json diff json:///tmp/file2.json -k version;branch"
(Pdb) c
F
======================================================================
FAIL: test_conf_cli_by_get_diff (conf_store.test_conf_cli.TestConfCli)
Test by retrieving a value using get api
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/932781/cortx-utils/py-utils/test/conf_store/test_conf_cli.py", line 86, in test_conf_cli_by_get_diff
    cmd = "conf json:///tmp/file1.json diff json:///tmp/file2.json -k version;branch"
AssertionError: False is not true : b'\'Namespace\' object has no attribute \'format\'\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.6/site-packages/cortx/utils/conf_store/conf_cli.py", line 334, in main\n    out = args.func(args)\n  File "/usr/lib/python3.6/site-packages/cortx/utils/conf_store/conf_cli.py", line 95, in diff\n    string_1 = ConfCli.get(args)\n  File "/usr/lib/python3.6/site-packages/cortx/utils/conf_store/conf_cli.py", line 81, in get\n    format_type = \'json\' if args.format == None else args.format\nAttributeError: \'Namespace\' object has no attribute \'format\'\n\n'

----------------------------------------------------------------------
Ran 1 test in 2.745s

FAILED (failures=1)
-bash-4.2$```

**Review by rohit-k-dwivedi — APPROVED** [review]
the changes works fine, it was issue with my testing

**Review by rahul-tripathi-git — APPROVED** [review]

**Comment by rahul-tripathi-git** [comment]
This PR has changes from confstore branch, hence it can not be merged. Please remove the irrelevant changes.

**Comment by suryakumar1024** [comment]
Raised different PR for the same
https://github.com/Seagate/cortx-utils/pull/767

**Pull request closed without merging**
