### PR TITLE
Update README.md: Correcting RPM version

### PR DESCRIPTION
**Pull request by daniarherikurniawan**
This existing README has this following line: `./jenkins/build.sh -v 2.0.0 -b 2` which will generate these following rpms:
```sh
cortx-py-utils-2.0.0-2_4e0eede.src.rpm
cortx-py-utils-2.0.0-2_4e0eede.noarch.rpm  
cortx-py-utils-2.0.0.tar.gz
```

However, when installing the RPM, the current script will look for version 1.0.0: `yum install -y cortx-py-utils-1.0.0-1.noarch.rpm`, which does not exist. Also, installing rpm should be executed by root. Therefore, the updated script should be: `sudo yum install -y cortx-py-utils-*.noarch.rpm`

Noted that this new input arg is utilizing `*` regex so that it can install any RPM regardless of the future version that will be generated.

-----
[View rendered py-utils/README.md](https://github.com/daniarherikurniawan/cortx-utils/blob/patch-1/py-utils/README.md)

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Review by rahul-tripathi-git — APPROVED** [review]
Looks good to me.

**Review by johnbent — APPROVED** [review]

**Comment by mukul-seagate11** [comment]
@Gatekeepers, Can the PR be reviewed & merged

**Review by sachinpunadikar — APPROVED** [review]
+1

**Comment by sachinpunadikar** [comment]
Its a change in ReadMe file, hence VM deployment check can be skipped. Merging the PR

**Pull request merged**
